"""
Topic: Multimodal — images (base64 + URL), PDFs, vision prompting
Cert notes section: "Images, PDFs and high-volume processing"
         "PDF is a document, treated the same as image file"
         "Multimodal prompting: same as text formatting, just resolve visual ambiguity"
Run: ../venv/bin/python script.py
"""

import os, base64, struct, zlib
from anthropic import Anthropic

client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

# ── Helper: generate a valid PNG programmatically (no external files needed) ──
def make_test_png(width: int = 60, height: int = 40) -> bytes:
    """Creates a small PNG with a gradient — pure stdlib, no Pillow needed."""
    def chunk(tag: bytes, data: bytes) -> bytes:
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    raw = b""
    for y in range(height):
        raw += b"\x00"   # filter type: None
        for x in range(width):
            # red gradient left→right, green gradient top→bottom, blue=120
            raw += bytes([int(x / width * 255), int(y / height * 255), 120])

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )

# ── 1. Image via base64 encoding ──────────────────────────────────────────
print("=== 1. Image via base64 ===")
png_bytes = make_test_png()
image_b64 = base64.standard_b64encode(png_bytes).decode("utf-8")

r1 = client.messages.create(
    model="claude-haiku-4-5-20251001",
    max_tokens=128,
    messages=[{
        "role": "user",
        "content": [
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": image_b64,
                }
            },
            {
                "type": "text",
                "text": "Describe the dominant colors in this image in one sentence."
            }
        ]
    }]
)
print(r1.content[0].text.strip())
print(f"Tokens: in={r1.usage.input_tokens}  out={r1.usage.output_tokens}")

# ── 2. Multiple images in one message ─────────────────────────────────────
print("\n=== 2. Multiple images ===")
png1 = make_test_png(60, 40)
png2 = make_test_png(80, 80)   # different size

r2 = client.messages.create(
    model="claude-haiku-4-5-20251001",
    max_tokens=128,
    messages=[{
        "role": "user",
        "content": [
            {"type": "text", "text": "I have two images:"},
            {"type": "image", "source": {"type": "base64", "media_type": "image/png",
                                          "data": base64.standard_b64encode(png1).decode()}},
            {"type": "text", "text": "and"},
            {"type": "image", "source": {"type": "base64", "media_type": "image/png",
                                          "data": base64.standard_b64encode(png2).decode()}},
            {"type": "text", "text": "Do both images have a gradient? Reply yes or no."},
        ]
    }]
)
print(r2.content[0].text.strip())

# ── 3. Save PNG to file and load from disk ────────────────────────────────
print("\n=== 3. Load image from disk ===")
png_path = os.path.join(os.path.dirname(__file__), "test_image.png")
with open(png_path, "wb") as f:
    f.write(make_test_png(100, 60))

with open(png_path, "rb") as f:
    disk_b64 = base64.standard_b64encode(f.read()).decode("utf-8")

r3 = client.messages.create(
    model="claude-haiku-4-5-20251001",
    max_tokens=64,
    messages=[{
        "role": "user",
        "content": [
            {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": disk_b64}},
            {"type": "text", "text": "What shape does this image appear to be — portrait or landscape?"}
        ]
    }]
)
print(r3.content[0].text.strip())
print(f"(Image saved to {png_path})")

# ── 4. Vision prompting best practices ───────────────────────────────────
print("\n=== 4. Resolve visual ambiguity in prompt ===")
r4 = client.messages.create(
    model="claude-haiku-4-5-20251001",
    max_tokens=128,
    messages=[{
        "role": "user",
        "content": [
            {"type": "image", "source": {"type": "base64", "media_type": "image/png",
                                          "data": base64.standard_b64encode(make_test_png()).decode()}},
            {
                "type": "text",
                "text": (
                    "This is a gradient test image generated by code. "   # resolve ambiguity: tell Claude what it is
                    "The X axis represents red intensity, Y axis represents green intensity. "
                    "What color would you expect to see in the top-left corner?"
                )
            }
        ]
    }]
)
print(r4.content[0].text.strip())

# ── 5. PDF pattern (structure — needs a real PDF file to run) ─────────────
print("\n=== 5. PDF pattern (code shown, not executed) ===")
print("""
# PDF is sent as a document block, not an image block:

with open("document.pdf", "rb") as f:
    pdf_b64 = base64.standard_b64encode(f.read()).decode()

response = client.messages.create(
    model="claude-sonnet-4-6",
    max_tokens=1024,
    messages=[{
        "role": "user",
        "content": [
            {
                "type": "document",
                "source": {
                    "type": "base64",
                    "media_type": "application/pdf",
                    "data": pdf_b64,
                }
            },
            {"type": "text", "text": "Summarize this document in 3 bullet points."}
        ]
    }]
)
""")

print("""
KEY TAKEAWAYS (cert notes):
- PDF and image use the same content block mechanism
- base64 encode the raw bytes; set media_type correctly
- Resolve visual ambiguity in the text part of your prompt
- Max image size: 5MB per image; max 20 images per request
- Token cost scales with image dimensions (larger = more tokens)
""")
