@startuml

package "Flow1" {
component one
component two
component thee
    one -> two: one way;
    two -> thee: two way;
}

package "Flow2" {
component one2
component two2
component two2d
component thee2
    one2 -> two2: one way;
    two2 -> thee2: two way;
}

component "Final Step" as final

thee -> final
thee2 -> final


one -[hidden]down-> one2
@enduml