spring:
  security:
    oauth2:
      client:
        registration:
          # Ця назва (keycloak) буде частиною redirect URL
          keycloak:
            client-id: spring-boot-app
            # Секрет, який ви скопіюєте з вкладки Credentials у Keycloak
            client-secret: pCXQEywt1PAL4fbbuqoiGZih2NZAIBAD
            # Набір дозволів, які ми просимо у Keycloak
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            # Шлях до вашого Realm (Spring автоматично підтягне всі метадані)
            issuer-uri: http://localhost:8080/realms/my-realm