server:
  port: 8091

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

  data:
    mongodb:
      uri: mongodb://user123:pass123@localhost:27017/testdb?authSource=admin
