###
POST http://localhost:8082/api/shorten
Content-Type: application/json

{
  "url": "https://football.ua/"
}

###
GET http://localhost:8085/redirect/F6p

###
DELETE http://localhost:8082/api/v1/admin/system/urls/Mp

