"""
Topic: Vision prompting — resolve visual ambiguity in the text part of the prompt
Cert notes section: "Multimodal prompting: same as text formatting, just resolve visual ambiguity"
Run: ../venv/bin/python _4_vision_prompting_ambiguity.py
"""

import os, base64
from anthropic import Anthropic
from _common import make_test_png

client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

print("=== Resolve visual ambiguity in prompt ===")
r4 = client.messages.create(
    model="claude-haiku-4-5-20251001",
    max_tokens=128,
    messages=[{
        "role": "user",
        "content": [
            {"type": "image", "source": {"type": "base64", "media_type": "image/png",
                                          "data": base64.standard_b64encode(make_test_png()).decode()}},
            {
                "type": "text",
                "text": (
                    "This is a gradient test image generated by code. "   # resolve ambiguity: tell Claude what it is
                    "The X axis represents red intensity, Y axis represents green intensity. "
                    "What color would you expect to see in the top-left corner?"
                )
            }
        ]
    }]
)
print(r4.content[0].text.strip())

print("""
KEY TAKEAWAYS (cert notes):
- Resolve visual ambiguity in the text part of your prompt (tell Claude what generated the image, what axes mean, etc.)
- Max image size: 5MB per image; max 20 images per request
- Token cost scales with image dimensions (larger = more tokens)
""")
